import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Fahim
 */
public class ReturnBook extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    ResultSet rs1;
    PreparedStatement pst1;

    /**
     * Creates new form ReturnBook
     *  @param s
     */
    
    public String name="";
    static String n;
    static String d;
    public String vbook_name;
    int vbook_quantity;
    public String vemail;
    public int vid;
    public int vmobile;
    
    public ReturnBook(String s) {
        initComponents();
        name=s;
        tableShow ();
        conn = db.java_db();
    }
    
    public void tableShow (){
        
        try{
            Connection conn = db.java_db();
            ResultSet rs;
            //PreparedStatement pst;
            String sql="select *from IssueBookConfirm where ibc_username = '"+name+"'" ;
            //pst=conn.prepareCall(sql);
            //pst.setString(1,name);
            CallableStatement pst = conn.prepareCall(sql);
            rs = pst.executeQuery(sql);
            resultTable.setModel(DbUtils.resultSetToTableModel(rs));
            conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        /*try{
            Connection conn = db.java_db();
            ResultSet rs;
            //PreparedStatement pst;
            String sql="SELECT ibc_date AS return_date from IssueBookConfirm where ibc_username = '"+name+"'" ;
            
            //pst=conn.prepareCall(sql);
            //pst.setString(1,name);
            CallableStatement pst = conn.prepareCall(sql);
            rs = pst.executeQuery(sql);
            retdate.setModel(DbUtils.resultSetToTableModel(rs));
            conn.close();
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }*/
        /*for(int i=0;i<retdate.getRowCount();i++)
        {
            String a=retdate.getValueAt(i, 0).toString();
            String temp="";
            String year="";
            String month=Character.toString(a.charAt(0))+Character.toString(a.charAt(1))+Character.toString(a.charAt(2))+" ";
            if(a.charAt(5)==',')
            {
                temp=Character.toString(a.charAt(4));
                year=Character.toString(a.charAt(7))+Character.toString(a.charAt(8))+Character.toString(a.charAt(9))+Character.toString(a.charAt(10));
            }
            else
            {
                temp=Character.toString(a.charAt(4))+Character.toString(a.charAt(5));
                year=""+Character.toString(a.charAt(8))+Character.toString(a.charAt(9))+Character.toString(a.charAt(10))+Character.toString(a.charAt(11));
                
            }
            int ret=Integer.parseInt(temp);
            ret=ret+7;
            
            String _final=month+Integer.toString(ret)+","+year;
            retdate.setValueAt(_final, i, 0);
        }*/
         //sql="SELECT DATEADD(day, 14, ib_date) AS return_date from IssueBook";
         
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, YYYY");
        Date date = new Date();
        todaysday.setText(sdf.format(date));
        //System.out.println(sdf.format(date)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        booksid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stdid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stdemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stdmobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        issuedate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        returndate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        todaysday = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 50, 67));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2), "Return Book Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 102, 0))); // NOI18N

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Return Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Serial id :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student's Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student's ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Issue Date :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Return Date :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Today's Date :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stdmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(stdname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stdemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(todaysday, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 351, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(booksid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(stdname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stdemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(todaysday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stdmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booksid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1109, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserPanel ah = new UserPanel(name);
        ah.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*DefaultTableModel model = (DefaultTableModel)resultTable.getModel();
        try{
            int selectedRowIndex = resultTable.getSelectedRow();
            model.removeRow(selectedRowIndex);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }*/
        
                                /////return Book code section;///////////////
        /*try{
            String sql2 = "update BookRegForm set book_quantity = book_quantity+1 where serial_id = ?";
            pst = conn.prepareStatement(sql2);
            String asd=booksid.getText();
            int a=Integer.parseInt(asd);
            //Jop
            //JOptionPane.showMessageDialog(null,a);
            //JOptionPane.showMessageDialog(null,"I came this far bvbn");
            //int Vsid=Integer.getInteger(search.getText());           
            vbook_quantity++;
            //pst.setInt   (1, vbook_quantity);
            pst.setInt (1, a);
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Increase book_quantity, done!!");
            //JOptionPane.showMessageDialog(null,"Book Added");
            //rs.close();
            pst.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
                   
        }*/
                             ///// delete from IssueBookConfirm /////
        /*try {
            String bsid = booksid.getText();
            JOptionPane.showMessageDialog(null,bsid);
            String sql3 = "delete from IssueBookConfirm where ibc_booksid = '"+bsid+"'";
            PreparedStatement pst = conn.prepareStatement(sql3);
            //ResultSet rs = pst.executeQuery();
            //resultTable02.setModel(DbUtils.resultSetToTableModel(rs));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"delete from IssueBookConfirm, done!!");
            //rs.close();
            //pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        } */
        
                            ///// fine calculation /////
        
        Calendar cal1 = new GregorianCalendar();
        Calendar cal2 = new GregorianCalendar();
        
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd,yyyy");
        
        Date date = null;
        try {
            
            date = sdf.parse(returndate.getText()); //return date
            
        } catch (ParseException ex) {
            
            Logger.getLogger(Fine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        cal1.setTime(date);
        try {
            
            date = sdf.parse(todaysday.getText()); //today's date
            
        } catch (ParseException ex) {
            
            Logger.getLogger(Fine.class.getName()).log(Level.SEVERE, null, ex);
        }       
        cal2.setTime(date);
        
        Integer days=daysBetween(cal1.getTime(),cal2.getTime());
        Integer fines=0;
        if(days>0){
           fines = days*10;
        }
        String dayss=String.valueOf(days);
        String fine="Fine is "+String.valueOf(fines)+" tk for "+dayss+" days";
        //String fine=String.valueOf(fines)+"tk";
        //JOptionPane.showMessageDialog(null,fine);
        //fine_amount.setText(fine);
        
                            ///// add info into FineShow database /////
        
        try{  
                //JOptionPane.showMessageDialog(null,"adding info into FineShow DB");
                String sql = "Insert into FineShow (fs_name,fs_id,fs_email,fs_mobile,fs_booksid,fs_issuedate,fs_returndate,fs_todaysdate) values (?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, stdname.getText());
                pst.setString(2, stdid.getText());
                pst.setString(3, stdemail.getText());
                pst.setString(4, stdmobile.getText());
                pst.setString(5, booksid.getText());
                pst.setString(6, issuedate.getText());
                pst.setString(7, returndate.getText());
                pst.setString(8, todaysday.getText());
                pst.execute();
                //JOptionPane.showMessageDialog(null,"information added into FineShow DB");
                //rs.close();
                //pst.close();
                       
        }catch(HeadlessException | SQLException e){       
            JOptionPane.showMessageDialog(null,e);                  
        }
        
                                ///// fine added into FineShow database /////
        
        String id = stdid.getText();
        //JOptionPane.showMessageDialog(null,"fine adding into FineShow DB");
        String sql="update FineShow set fs_fine='"+fine+"' where fs_id='"+id+"'";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            //ResultSet rs = pst.executeQuery();
            //resultTable02.setModel(DbUtils.resultSetToTableModel(rs));
            JOptionPane.showMessageDialog(null,"please wait for admin confirmation..!!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public int daysBetween(Date d1, Date d2) {
        return (int)( (d2.getTime() - d1.getTime()) / (1000 * 60 * 60 * 24));
    }
    
    private void resultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)resultTable.getModel();

        // get the selected row index
       int selectedRowIndex = resultTable.getSelectedRow();
       
        // set the selected row data into jtextfields
       stdname.setText(model.getValueAt(selectedRowIndex, 0).toString());
       stdid.setText(model.getValueAt(selectedRowIndex, 1).toString());
       stdemail.setText(model.getValueAt(selectedRowIndex, 2).toString());
       stdmobile.setText(model.getValueAt(selectedRowIndex, 3).toString());
       booksid.setText(model.getValueAt(selectedRowIndex, 4).toString());
       issuedate.setText(model.getValueAt(selectedRowIndex, 7).toString());
       returndate.setText(model.getValueAt(selectedRowIndex, 8).toString());
       //email.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_resultTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new ReturnBook("Fahim").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField booksid;
    private javax.swing.JTextField issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField returndate;
    private javax.swing.JTextField stdemail;
    private javax.swing.JTextField stdid;
    private javax.swing.JTextField stdmobile;
    private javax.swing.JTextField stdname;
    private javax.swing.JTextField todaysday;
    // End of variables declaration//GEN-END:variables
}
